blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://discord.gg/rbUG6SpRAM
    about: Please ask and answer questions here
  - name: List a token
    url: https://github.com/AnimeSwap/default-token-list#adding-a-token
    about: Any requests to add a token to AnimeSwap should go here
